package cn.com.ddhj.mapper;

import cn.com.ddhj.model.TReport;

public interface TReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbggenerated
     */
    int insert(TReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbggenerated
     */
    int insertSelective(TReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbggenerated
     */
    TReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TReport record);
}